# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8a511df825b553fa641abda94228d06b3d4ca812125c912f1329b55c8a496b1192549129b7ba2ea2d1a39486568e516b3f87bc681ec13f97ce42100bc7a49f0

test:
  secret_key_base: 3b2ad567874bd5995ae786cfda09e8bc14ca859fe3e408b1c8df3e1feab2ace8df87d93e7285048af7f75e098e81793e99cf574e11e9ac316e21e6dd3bec67a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
